version: 2
updates:
  - package-ecosystem: cargo
    schedule:
      interval: monthly
    directories:
      - /
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /.docker
    schedule:
      interval: monthly
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
