[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "A template worker application for Clouflare Workers"
edition = "2024"
keywords = ["axum", "cloudflare", "template", "wasm"]
license = "Apache-2.0"
name = "template-rs-cloudflare"
publish = false
repository = "https://github.com/FL03/template-rs-cloudflare.git"
version = "0.0.0"

resolver = "3"

[features]
default = [
    "cf",
    "json",
    "time",
    "wasm",
]

full = [
    "default",
    "chrono",
    "rand",
    "tracing",
    "uuid",
]

# ************* [FF:Dependencies] *************
cf = [
    "dep:worker",
    "dep:worker-macros",
]

chrono = ["dep:chrono"]

config = ["dep:config"]

http1 = [
    "axum/http1"
]

http2 = [
    "axum/http2"
]

json = [
    "dep:serde_json",
    "axum/json",
]

rand = [
    "dep:rand",
    "dep:rand_distr",
    "uuid?/v4",
    "rng"
]

rng = [
    "dep:getrandom"
]

time = ["dep:time"]

tracing = ["dep:tracing"]

uuid = [
    "dep:uuid",
    "uuid?/v3",
    "uuid?/v5",
]

# ************* [FF:Environments] *************
wasi = []

wasm = [
    "getrandom?/wasm_js",
    "uuid?/js",
]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = false
test = true

[dependencies]
config = { optional = true, version = "0.15" }
# api
axum = { default-features = false, features = ["macros"], version = "0.8" }
# data & serialization
bytes = { features = ["serde"], version = "1" }
serde = { features = ["derive"], version = "1" }
serde_derive = { version = "1" }
serde_json = { optional = true, version = "1" }
# error handling
anyhow ={ version = "1" }
thiserror = { version = "2" }
# logging
tracing = { features = ["attributes", "log"], optional = true, version = "0.1" }
# randomization
getrandom = { optional = true, version = "0.3" }
rand = { optional = true, version = "0.9" }
rand_distr = { optional = true, version = "0.5" }
uuid = { features = ["serde"], optional = true, version = "1" }
# middleware & networking
tower-service = { version =  "0.3" }
url = { version = "1" }
# macros
paste = "1"
smart-default = { version = "0.7" }
strum = { features = ["derive"], version = "0.27" }
# time
chrono = { features = ["serde"], optional = true, version = "0.4" }
time = { features = ["serde"], optional = true, version = "0.3" }
# cloudflare
worker = { features = ["axum", "http"], optional = true, version = "0.5" }
worker-macros = { features = ["http"], optional = true, version = "0.5" }

[target.wasm32-unknown-unknown.dependencies]
console_error_panic_hook = "0.1"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
codegen-units = 1
lto = true
strip = true
