[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "A template worker application for Clouflare Workers"
edition = "2021"
keywords = ["axum", "cloudflare", "template", "wasm"]
license = "Apache-2.0"
name = "template-rs-cloudflare"
publish = false
repository = "https://github.com/FL03/template-rs-cloudflare.git"
version = "0.0.0"

[features]
default = [
    "wasm",
]

full = [
    "default",
]

# ********* [FF] Dependencies *********


# ********* [FF] Environments *********
std = []

wasi = []

wasm = []

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = false
test = true

[build-dependencies]

[dev-dependencies]

[dependencies]
anyhow = "1"
paste = "1"
serde_json = "1"
tower-service = "0.3"

[dependencies.axum]
default-features = false
features = [
    "json", 
    "macros"
]
version = "0.8"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.strum]
features = ["derive"]
version = "0.26"

[dependencies.uuid]
features = ["js", "serde", "v4"]
version = "1"

[dependencies.worker]
features = [
    "axum", 
    "http"
]
version = "0.4"

[dependencies.worker-macros]
features = ["http"]
version = "0.4"

[target.wasm32-unknown-unknown.dependencies]
console_error_panic_hook = "0.1"
getrandom = { features = ["js"], version = "0.2" }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
codegen-units = 1
lto = true
strip = true