[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "A template worker application for Clouflare Workers"
edition = "2021"
name = "template-rs-cloudflare"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1"
tower-service = "0.3"

[dependencies.axum]
default-features = false
features = []
version = "0.7"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.worker]
features = ["axum", "http"]
version = "0.4"

[dependencies.worker-macros]
features = ["http"]
version = "0.4"

[target.wasm32-unknown-unknown.dependencies]
console_error_panic_hook = "0.1"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false