compatibility_date = "2025-05-16"
main = "build/worker/shim.mjs"
name = "template-rs-cloudflare"
workers_dev = false

[build]
command = "cargo install -q worker-build && worker-build --locked --release --features web"

[observability.logs]
enabled = true

[[routes]]
custom_domain = true
pattern = "worker.scsys.io"
zone_name = "scsys.io"


# ************* [Environments] *************
[env.production]
name = "production"
routes = [
  { pattern = "worker.scsys.io/*", zone_name = "scsys.io" },
  "template-rs-cloudflare-scsys.workers.dev",
]

[env.preview]
name = "preview"
routes = [
  { pattern = "worker-dev.scsys.io/*", zone_name = "scsys.io" },
  "*-template-rs-cloudflare-scsys.workers.dev/*",
]

# ************* [Variables] *************
[vars]
RUST_BACKTRACE = 1
RUST_LOG="rscloud::worker=debug,info"