compatibility_date = "2025-05-16"
main = "build/worker/shim.mjs"
name = "template-rs-cloudflare"

workers_dev = false

[build]
command = "worker-build --release -F app"

[observability.logs]
enabled = true

[route]
pattern = "worker.scsys.io"
zone_name = "scsys.io"

# ************* [Environments] *************
[env.staging]
name = "worker-staging"

[env.staging.route]
pattern = "stag.scsys.io"
zone_name = "scsys.io"

# ************* [Variables] *************
[vars]
RUST_BACKTRACE = 1