compatibility_date = "2025-05-16"
compatibility_flags = [ "nodejs_compat" ]
main = "build/worker/shim.mjs"
name = "template-rs-cloudflare"
# enable the *.workers.dev endpoint for the project
workers_dev = true

[assets]
binding = "ARTIFACTS"
directory = "build"

[build]
command = "npm run worker:build"



[observability.logs]
enabled = true

# ************* [Variables] *************

[vars]
RUST_BACKTRACE = 1
RUST_LOG="rscloud=debug,info"

# ************* [routes] *************

[[routes]]
custom_domain = true
pattern = "worker.scsys.io"
zone_name = "scsys.io"

# ************* [Environments] *************

[env.production]
name = "production"
routes = [
  { pattern = "worker.scsys.io/*", zone_name = "scsys.io" },
  "template-rs-cloudflare-scsys.workers.dev/**",
]

[env.preview]
name = "preview"
