compatibility_date = "2025-16-05"
main = "build/worker/shim.mjs"
name = "template-rs-cloudflare"

workers_dev = false

[build]
command = "worker-build --release -d build -F app"

[observability.logs]
enabled = true

[route]
pattern = "worker.scsys.io"
zone_name = "scsys.io"

# ********* [Env] Staging *********
[env.staging]
name = "worker-staging"

[env.staging.route]
pattern = "stag.scsys.io"
zone_name = "scsys.io"

# ************* [Environment variables] *************
[vars]
# Add your environment variables here