compatibility_date = "2024-10-04"
main = "build/worker/shim.mjs"
name = "template-rs-cloudflare"

workers_dev = false

[build]
command = "worker-build --release"

[route]
pattern = "worker.scattered-systems.com"
zone_name = "scattered-systems.com"

# ********* [Env] Production *********
[env.production]
name = "worker"

[env.production.route]
pattern = "worker.scattered-systems.com/api/*"
zone_name = "scattered-systems.com"

# ********* [Env] Staging *********
[env.staging]
name = "worker-staging"

[env.staging.route]
pattern = "staging.scattered-systems.com"
zone_name = "scattered-systems.com"
