name: deploy

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: 22
  RUSTC_VERSION: 1.86.0
  WRANGLER_VERSION: 4.15.2
  STAGE: ${{ github.event.inputs.environment || 'Preview' }}

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main, master ]
    tags: [ v*.*.*, "*-alpha", "*-beta", "*-canary", "*-nightly" ]
  release:
    types: [ prereleased, released ]
  repository_dispatch:
    types: [ cloudflare, deploy ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: Preview
        type: choice
        options: [ Preview, Production ]

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  preview:
    environment: 
      name: Preview
      url: ${{ steps.deploy.outputs.deployment-url }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout the source code
        uses: actions/checkout@v4
      - 
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache-workspaces: true
          target: wasm32-unknown-unknown
      - 
        id: deploy
        name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: ${{ env.WRANGLER_VERSION }}
  production:
    if: github.event_name == 'release' && github.event.action == 'released' || github.env.STAGE == 'Production'
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - 
        name: Checkout the source code
        uses: actions/checkout@v4
      - 
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache-workspaces: true
          target: wasm32-unknown-unknown
      - 
        id: deploy
        name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: ${{ env.WRANGLER_VERSION }}
