name: docker

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CONTAINER_IMAGE_NAME: ${{ github.event.repository.name }}
  CONTAINER_PLATFORMS: linux/amd64
  RUSTC_VERSION: 1.86.0

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, reopened, synchronize ]
  push:
    tags: [ v*.*.*, "*-nightly" ]
  repository_dispatch:
    types: [ docker ]
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  dockerhub:
    env:
      CONTAINER_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.env.CONTAINER_IMAGE_NAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      CONTAINER_REGISTRY_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            dockerfile: Dockerfile
    runs-on: ${{ matrix.os }}
    steps:
    - 
      name: checkout
      uses: actions/checkout@v4
    - 
      id: metadata
      name: Container Metadata
      uses: docker/metadata-action@v5
      with:
        flavor: latest=true
        images: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha  
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Authenticate DockerHub
      uses: docker/login-action@v3
      with:
        password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}
        username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
    -
      id: bnp
      name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        file: ./.docker/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: ${{ steps.metadata.outputs.labels }}
        platforms: ${{ env.CONTAINER_PLATFORMS }}
        tags: ${{ steps.metadata.outputs.tags }}
    - 
      id: attestation
      continue-on-error: true
      name: Establish Provenance
      uses: actions/attest-build-provenance@v2
      with:
        push-to-registry: false
        subject-digest: ${{ steps.bnp.outputs.digest }}
        subject-name: ${{ env.CONTAINER_IMAGE_NAME}}
