name: release

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      environment:
        default: 'production'
        description: 'Environment to deploy to'
        required: true
        type: environment

permissions: write-all

jobs:
  cloudflare:
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      -
        name: rustup
        run: |
          rustup default stable
          rustup update
      -
        name: setup wrangler
        run: cargo install --locked wasm-pack worker-build
      - 
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
        name: production 
        run: npx wrangler deploy --minify