name: rust

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

on:
  pull_request:
    branches: [ main, master, ]
    types: [ opened, reopened, closed ]
  push:
    tags: [ v*, "*-nightly" ]
  repository_dispatch:
    types: [ rust ]
  workflow_dispatch:

permissions: write-all

jobs:
  workspace:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os:  [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: setup rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache-workspaces: true
      - 
        name: cache
        uses: Swatinem/rust-cache@v2
      - 
        name: build
        run: cargo build -r --workspace --features full
      - 
        name: test
        run: cargo test -r --workspace --features full
      - 
        name: benchmark
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: cargo bench -v --workspace --features full
          